version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile-slim
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            DEBUG: ${DEBUG}
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./db:/var/lib/postgresql/scripts
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    db-data:
    pgadmin-data:
